CREATE TABLE IF NOT EXISTS BRAND
(
    ID   BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(255),
    CONSTRAINT PK_BRAND PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID   BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(255),
    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PRICE_LIST
(
    ID   BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(255),
    CONSTRAINT PK_PRICE_LIST PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PRICE
(
    ID            BIGINT AUTO_INCREMENT               NOT NULL,
    START_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    END_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRICE         DOUBLE PRECISION                    NOT NULL,
    CURR          VARCHAR(3)                          NOT NULL,
    PRIORITY      INTEGER                             NOT NULL,
    BRAND_ID      BIGINT                              NOT NULL,
    PRODUCT_ID    BIGINT                              NOT NULL,
    PRICE_LIST_ID BIGINT                              NOT NULL,
    CONSTRAINT PK_PRICE PRIMARY KEY (ID),
    CONSTRAINT FK_PRICE_ON_BRAND FOREIGN KEY (BRAND_ID) REFERENCES BRAND (ID),
    CONSTRAINT FK_PRICE_ON_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
    CONSTRAINT FK_PRICE_ON_PRICE_LIST FOREIGN KEY (PRICE_LIST_ID) REFERENCES PRICE_LIST (ID)
);

CREATE VIEW IF NOT EXISTS PRICE_VIEW AS
(
SELECT PR.ID, PD.ID AS PRODUCT_ID, BR.ID AS BRAND_ID, PL.NAME, PR.START_DATE, PR.END_DATE, PR.PRICE, PR.PRIORITY
FROM PRICE PR
         INNER JOIN PRODUCT PD ON PR.PRODUCT_ID = PD.ID
         INNER JOIN BRAND BR ON PR.BRAND_ID = BR.ID
         INNER JOIN PRICE_LIST PL ON PR.PRICE_LIST_ID = PL.ID
    );